import { Router, type IRouter } from "express";
import { Token, User, RationCard } from "@workspace/db";
import { GenerateTokenBody, GetAllTokensQueryParams } from "@workspace/api-zod";
import { sendTokenConfirmationEmail, sendRationDistributionEmail } from "../lib/mailer";
import { getRationEntitlement, generateRationMessage } from "../services/rationService";

const router: IRouter = Router();

function generateTokenNumber(): string {
  const prefix = "TKN";
  const date = new Date();
  const dateStr = `${date.getFullYear()}${String(date.getMonth() + 1).padStart(2, "0")}${String(date.getDate()).padStart(2, "0")}`;
  const random = Math.floor(1000 + Math.random() * 9000);
  return `${prefix}-${dateStr}-${random}`;
}

router.post("/tokens/generate", async (req, res): Promise<void> => {
  const userId = (req.session as any)?.userId;
  if (!userId) {
    res.status(401).json({ message: "Not authenticated" });
    return;
  }

  const parsed = GenerateTokenBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ message: parsed.error.message });
    return;
  }

  try {
    // Check if a token already exists for this ration card that is not distributed
    const existingToken = await Token.findOne({
      rationCardNumber: parsed.data.rationCardNumber,
      status: { $in: ["pending", "verified"] }
    });

    if (existingToken) {
      // Check if the existing token is older than 25 days
      const twentyFiveDaysAgo = new Date();
      twentyFiveDaysAgo.setDate(twentyFiveDaysAgo.getDate() - 25);
      
      if (existingToken.createdAt > twentyFiveDaysAgo) {
        res.status(400).json({ 
          message: "Token is already generated by family member check my tokens page",
          existingToken: {
            tokenNumber: existingToken.tokenNumber,
            status: existingToken.status,
            createdAt: existingToken.createdAt
          }
        });
        return;
      }
      // If token is older than 25 days, allow generating a new one
      console.log("Allowing new token generation - existing token is older than 25 days");
    }

    const tokenNumber = generateTokenNumber();

    // Get user and ration card details for ration calculation
    const user = await User.findById(userId);
    const rationCard = await RationCard.findOne({ rationCardNumber: parsed.data.rationCardNumber });
    const cardType = rationCard?.cardType ;
    const familyMembers = rationCard?.familyMembers?.length || 0;
    
    // Calculate ration entitlement
    const entitlement = getRationEntitlement(cardType, familyMembers);
    
    const token = await Token.create({
      tokenNumber,
      rationCardNumber: parsed.data.rationCardNumber,
      holderName: parsed.data.selectedMembers[0] || "Unknown",
      selectedMembers: parsed.data.selectedMembers,
      verificationType: parsed.data.verificationType,
      status: "pending",
      userId,
      rationDetails: {
        cardType,
        familyMembers,
        entitlement,
        month: new Date().toLocaleString('default', { month: 'long' }),
        year: new Date().getFullYear(),
        shopName: user?.fairPriceShop || "FPS-001"
      },
      capturedFaceData: (req.body as any).capturedFaceData || null,
      faceVerificationMember: (req.body as any).faceVerificationMember || null,
    });

  if (user) {
    sendTokenConfirmationEmail(
      user.email,
      `${user.firstName} ${user.lastName}`,
      token.tokenNumber,
      token.rationCardNumber,
      token.selectedMembers as string[],
      token.verificationType,
    ).catch(() => {});
  }

  res.status(201).json({
    id: token._id.toString(),
    tokenNumber: token.tokenNumber,
    rationCardNumber: token.rationCardNumber,
    holderName: token.holderName,
    selectedMembers: token.selectedMembers,
    verificationType: token.verificationType,
    status: token.status,
    createdAt: token.createdAt.toISOString(),
    updatedAt: token.updatedAt.toISOString(),
    rationDetails: token.rationDetails,
  });
  } catch (error) {
    res.status(500).json({ message: "Failed to generate token" });
  }
});

router.get("/tokens/my-tokens", async (req, res): Promise<void> => {
  const userId = (req.session as any)?.userId;
  if (!userId) {
    res.status(401).json({ message: "Not authenticated" });
    return;
  }

  const tokens = await Token.find({ userId }).sort({ createdAt: -1 });

  res.json(
    tokens.map((t) => ({
      id: t._id.toString(),
      tokenNumber: t.tokenNumber,
      rationCardNumber: t.rationCardNumber,
      holderName: t.holderName,
      selectedMembers: t.selectedMembers,
      verificationType: t.verificationType,
      status: t.status,
      createdAt: t.createdAt.toISOString(),
      updatedAt: t.updatedAt.toISOString(),
      rationDetails: t.rationDetails,
    })),
  );
});

router.get("/admin/tokens", async (req, res): Promise<void> => {
  const role = (req.session as any)?.role;
  if (role !== "admin") {
    res.status(403).json({ message: "Admin access required" });
    return;
  }

  const params = GetAllTokensQueryParams.safeParse(req.query);

  let query: any = { status: params.success && params.data.status ? params.data.status : { $exists: true } };

  const tokens = await Token.find(query)
    .populate('userId', 'name email')
    .sort({ createdAt: -1 });

  res.json(
    tokens.map((t) => ({
      id: t._id.toString(),
      tokenNumber: t.tokenNumber,
      rationCardNumber: t.rationCardNumber,
      holderName: t.holderName,
      userName: (t.userId as any)?.name || 'Unknown',
      userEmail: (t.userId as any)?.email || 'Unknown',
      selectedMembers: t.selectedMembers,
      verificationType: t.verificationType,
      status: t.status,
      createdAt: t.createdAt.toISOString(),
      updatedAt: t.updatedAt.toISOString(),
      hasCapturedFace: !!(t as any).capturedFaceData,
      faceVerificationMember: (t as any).faceVerificationMember || null,
    })),
  );
});

// Get face comparison data for a specific token (admin only)
router.get("/admin/tokens/:tokenId/face-comparison", async (req, res): Promise<void> => {
  const role = (req.session as any)?.role;
  if (role !== "admin") {
    res.status(403).json({ message: "Admin access required" });
    return;
  }

  try {
    const token = await Token.findById(req.params.tokenId);
    if (!token) {
      res.status(404).json({ message: "Token not found" });
      return;
    }

    if (!(token as any).capturedFaceData) {
      res.status(404).json({ message: "No face data for this token" });
      return;
    }

    // Get reference face from ration card
    const card = await RationCard.findOne({ rationCardNumber: token.rationCardNumber });
    const memberName = (token as any).faceVerificationMember;
    const member = card?.familyMembers?.find((m: any) => m.name === memberName);

    res.json({
      tokenNumber: token.tokenNumber,
      memberName,
      capturedFaceData: (token as any).capturedFaceData,
      referenceFaceData: member?.faceData || null,
    });
  } catch (error) {
    res.status(500).json({ message: "Failed to get face comparison data" });
  }
});

router.post("/admin/tokens/:tokenId/verify", async (req, res): Promise<void> => {
  const role = (req.session as any)?.role;
  if (role !== "admin") {
    res.status(403).json({ message: "Admin access required" });
    return;
  }

  const tokenId = req.params.tokenId;
  console.log("Verify token attempt - TokenId:", tokenId);

  try {
    // Use the tokenId directly as ObjectId string
    const token = await Token.findByIdAndUpdate(
      tokenId,
      { status: "verified", updatedAt: new Date() },
      { new: true }
    ).populate('userId', 'name email');

    if (!token) {
      console.log("Token not found with ID:", tokenId);
      res.status(404).json({ message: "Token not found" });
      return;
    }
    
    console.log("Found token:", token.tokenNumber, "Current status:", token.status);

    if (!token) {
      console.log("Failed to update token");
      res.status(404).json({ message: "Token not found" });
      return;
    }

    console.log("Token updated successfully to verified status");

    res.json({
      id: token._id.toString(),
      tokenNumber: token.tokenNumber,
      rationCardNumber: token.rationCardNumber,
      holderName: token.holderName,
      userName: (token.userId as any)?.name || "",
      userEmail: (token.userId as any)?.email || "",
      selectedMembers: token.selectedMembers,
      verificationType: token.verificationType,
      status: token.status,
      createdAt: token.createdAt.toISOString(),
      updatedAt: token.updatedAt.toISOString(),
    });
  } catch (error) {
    console.error("Verify token error:", error);
    res.status(500).json({ message: "Failed to verify token" });
  }
});

router.post("/admin/tokens/:tokenId/distribute", async (req, res): Promise<void> => {
  const role = (req.session as any)?.role;
  if (role !== "admin") {
    res.status(403).json({ message: "Admin access required" });
    return;
  }

  const tokenId = req.params.tokenId;

  const token = await Token.findByIdAndUpdate(
    tokenId,
    { status: "distributed", updatedAt: new Date() },
    { new: true }
  ).populate('userId', 'name email');

  if (!token) {
    res.status(404).json({ message: "Token not found" });
    return;
  }

  // Send distribution email to the user
  let emailSent = false;
  const userEmail = (token.userId as any)?.email;
  if (userEmail && token.rationDetails) {
    try {
      const emailResult = await sendRationDistributionEmail(userEmail, {
        rationCardNumber: token.rationCardNumber,
        cardType: token.rationDetails.cardType,
        familyMembers: token.rationDetails.familyMembers,
        shopName: token.rationDetails.shopName || "Main Ration Center"
      });
      emailSent = emailResult.success;
      req.log.info({ userEmail, tokenNumber: token.tokenNumber, emailSent }, "Distribution email attempt");
    } catch (emailError) {
      req.log.error({ emailError, tokenNumber: token.tokenNumber }, "Failed to send distribution email");
    }
  }

  res.json({
    id: token._id.toString(),
    tokenNumber: token.tokenNumber,
    rationCardNumber: token.rationCardNumber,
    holderName: token.holderName,
    userName: (token.userId as any)?.name || "",
    userEmail: (token.userId as any)?.email || "",
    selectedMembers: token.selectedMembers,
    verificationType: token.verificationType,
    status: token.status,
    createdAt: token.createdAt.toISOString(),
    updatedAt: token.updatedAt.toISOString(),
    emailSent,
  });
});

router.post("/admin/tokens/bulk-distribute", async (req, res): Promise<void> => {
  const role = (req.session as any)?.role;
  if (role !== "admin") {
    res.status(403).json({ message: "Admin access required" });
    return;
  }

  const { tokenIds } = req.body;

  if (!tokenIds || !Array.isArray(tokenIds) || tokenIds.length === 0) {
    res.status(400).json({ message: "Token IDs array is required" });
    return;
  }

  try {
    // Get the tokens with user details before updating
    const tokensToDistribute = await Token.find({ 
      _id: { $in: tokenIds }, 
      status: "verified" 
    }).populate('userId');

    if (tokensToDistribute.length === 0) {
      res.status(400).json({ message: "No verified tokens found to distribute" });
      return;
    }

    // Update token status
    const tokens = await Token.updateMany(
      { _id: { $in: tokenIds }, status: "verified" },
      { status: "distributed", updatedAt: new Date() }
    );

    // Send distribution emails to all users
    let emailsSent = 0;
    let emailsFailed = 0;
    
    const emailPromises = tokensToDistribute.map(async (token) => {
      try {
        const user = token.userId as any;
        
        if (user?.email && token.rationDetails) {
          const emailResult = await sendRationDistributionEmail(user.email, {
            rationCardNumber: token.rationCardNumber,
            cardType: token.rationDetails.cardType,
            familyMembers: token.rationDetails.familyMembers,
            shopName: token.rationDetails.shopName || "Main Ration Center"
          });
          
          if (emailResult.success) {
            emailsSent++;
            req.log.info({ userEmail: user.email, tokenNumber: token.tokenNumber }, "Distribution email sent successfully");
          } else {
            emailsFailed++;
            req.log.error({ userEmail: user.email, error: emailResult.error }, "Failed to send distribution email");
          }
        }
      } catch (emailError) {
        emailsFailed++;
        req.log.error({ emailError, tokenNumber: token.tokenNumber }, "Failed to send distribution email");
      }
    });

    // Wait for all emails to be sent
    await Promise.allSettled(emailPromises);

    res.json({
      message: `Successfully distributed ${tokens.modifiedCount} tokens`,
      distributedCount: tokens.modifiedCount,
      emailsSent,
      emailsFailed
    });
  } catch (error) {
    console.error("Bulk distribute error:", error);
    res.status(500).json({ message: "Failed to distribute tokens" });
  }
});

router.get("/admin/dashboard-stats", async (req, res): Promise<void> => {
  const role = (req.session as any)?.role;
  if (role !== "admin") {
    res.status(403).json({ message: "Admin access required" });
    return;
  }

  const allTokens = await Token.find({});

  const today = new Date();
  today.setHours(0, 0, 0, 0);

  const stats = {
    totalTokens: allTokens.length,
    pendingTokens: allTokens.filter((t) => t.status === "pending").length,
    verifiedTokens: allTokens.filter((t) => t.status === "verified").length,
    distributedTokens: allTokens.filter((t) => t.status === "distributed").length,
    todayTokens: allTokens.filter((t) => t.createdAt >= today).length,
  };

  res.json(stats);
});

router.get("/admin/recent-activity", async (req, res): Promise<void> => {
  const role = (req.session as any)?.role;
  if (role !== "admin") {
    res.status(403).json({ message: "Admin access required" });
    return;
  }

  const tokens = await Token.find({})
    .populate('userId', 'name')
    .sort({ updatedAt: -1 })
    .limit(20);

  const activityMap: Record<string, string> = {
    pending: "Token Generated",
    verified: "Token Verified",
    distributed: "Ration Distributed",
  };

  res.json(
    tokens.map((t) => {
      let userName = "Unknown";
      
      if (t.status === "pending") {
        const user = (t.userId as any);
        if (user && user.firstName && user.lastName) {
          userName = `${user.firstName} ${user.lastName}`;
        } else {
          userName = t.holderName || "Unknown";
        }
      } else if (t.status === "verified" || t.status === "distributed") {
        userName = "GovtAdmin";
      }
      
      return {
        id: t._id.toString(),
        tokenNumber: t.tokenNumber,
        action: activityMap[t.status] || t.status,
        userName,
        timestamp: t.updatedAt.toISOString(),
      };
    }),
  );
});

export default router;
